FROM golang:1.21 AS builder

WORKDIR /app
COPY . .
RUN go build -o zep ./cmd/server

FROM debian:bullseye-slim
WORKDIR /app
COPY --from=builder /app/zep /app/
COPY --from=builder /app/migrations /app/migrations
COPY --from=builder /app/web /app/web
COPY --from=builder /app/.env /app/.env
EXPOSE 8000

CMD ["./zep"]

